{
    "__comment":  "Snakemake configuration for e5 cluster infrastructure",
    "DATAIN": "/ceph/FlavourTagging/NTuples/Run3/MC",
    "DATAOUT": "/ceph/users/togasa/FlavourTagging/NTuples/MC",
    "REPO": "/ceph/users/togasa/classical-taggers",
    "nCPUs":      "1",
    "LOCALTMP": "/ceph/users/togasa/classical-taggers/outdir/tmp",
    "LOG": "/ceph/users//togasa/classical-taggers/outdir/log",
}