from os.path import join, exists, dirname, basename, splitext, split
from os import makedirs
import numpy as np
import os
from copy import deepcopy


try:
    data = config['RAW_DATA']
    repo = config['REPO']
    modified_MC = config['MODIFIED_MC']
except:
    raise RuntimeError("Make sure to specify snakemake config")


taggers_conf = {
    #'Bu2JpsiK': ['OSKaon', 'OSElectron', 'OSMuon'],
    #'Bd2JpsiKst': ['SSPion', 'SSProton', 'OSKaon', 'OSElectron', 'OSMuon'],
    'Bs2DsPi': ['SSKaon', 'OSKaon', 'OSElectron', 'OSMuon'],
    # 'Bd2DmPi': ['SSPion', 'SSProton', 'OSKaon', 'OSElectron', 'OSMuon',],
    # 'Bs2JpsiPhi': ['OSKaon', 'OSElectron', 'OSMuon', 'SSPion', 'SSProton', 'SSKaon']
}
def find_tree_name(decay):
    if decay == 'Bs2JpsiPhi':
        return 'BsToJpsiPhi_Detached/DecayTree'
    if decay == 'Bs2DsPi':
        return 'BdToDsmPi_DsmToKpKmPim/DecayTree' # For file of type root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/anaprod/lhcb/MC/2024/MC.ROOT/00229398/0000/00229398_00000001_1.mc.root
    if decay == 'Bu2JpsiK':
        return 'BuToJpsiKplus_JpsiToMuMu_Detached/DecayTree'
    if decay == 'Bd2JpsiKst':
        return 'BdToJpsiKstar_JpsiToMuMu_Detached/DecayTree'
    else:
        return 'Tuple/DecayTree'

# Extract decay used for training the tagger, used for the model path
def extract_decay(tagger):
    if tagger in ['OSKaon', 'OSMuon', 'OSElectron']:
        return 'Bu2JpsiK'
    elif tagger == 'SSKaon':
        return 'Bs2DsPi'
    elif tagger in ['SSPion', 'SSProton']:
        return 'Bd2JpsiKst'
    else:
        raise ValueError(f"Unknown tagger: {tagger}")

# Stripping s24c2 MagUp - Block 1 and 2
# The txt files has been generated with ls /eos/lhcb/grid/prod/lhcb/anaprod/lhcb/LHCb/Collision24/DATA24.ROOT/00266999/0000/*.root > block12_list.txt
def select_input_files(decay):
    """Read block1_list_Nicolas_<decay>.txt and return
    a list of full EOS URLs for that decay."""
    eosdir = 'root://eoslhcb.cern.ch/'
    txt = f"block12_list_{decay}.txt"
    with open(txt, "r") as f:
        lines = [line.strip() for line in f]
    return [eosdir + path for path in lines]

raw_data = {
    decay: [
        join(data, 'withUT_MC_2024', '1_raw', decay, basename(path))
        for path in select_input_files(decay)
    ]
    for decay in taggers_conf
}
selected_data = {}
for decay, path_list in raw_data.items():
    selected_data.update({decay: {}})
    for tagger in taggers_conf[decay] :
        selected_data[decay].update({tagger: [f.replace('1_raw', f'3_selected').replace(decay, f'{decay}/{tagger}/allBKGCAT_notSamePV_noOSP_SSK/union_PROBNN') for f in path_list]})

tagged_data = {}
for decay, path_list in raw_data.items():
    tagged_data.update({decay: {}})
    for tagger in taggers_conf[decay] :
        tagged_data[decay].update({tagger: [f.replace('1_raw', f'4_tagged').replace(decay, f'{decay}/{tagger}/allBKGCAT_notSamePV_noOSP_SSK/union_PROBNN') for f in path_list]})



rule all:
    input: 
        tagged_data['Bs2DsPi']['SSKaon'],
        #tagged_data['Bs2DsPi']['OSKaon'],

        #tagged_data['Bs2DsPi']['OSElectron'],
        #tagged_data['Bs2DsPi']['OSMuon'],
        #tagged_data['Bu2JpsiK']['OSKaon'],
        #tagged_data['Bu2JpsiK']['OSMuon'],
        #tagged_data['Bu2JpsiK']['OSElectron'],
        #tagged_data['Bd2JpsiKst']['SSPion'],
        #tagged_data['Bd2JpsiKst']['SSProton'],
        #tagged_data['Bd2JpsiKst']['OSKaon'],
        #tagged_data['Bd2JpsiKst']['OSMuon'],
        #tagged_data['Bd2JpsiKst']['OSElectron'],

        #data['Bu2JpsiK'],
        #data['Bd2JpsiKst'],
        # Add taggers on Bs

#phis ntuples are huge, they contain all the decays, so this first rule is to populate 1_raw directory with only the interesting decay
RAW_SETTINGS = {
    "Bu2JpsiK": "root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/anaprod/lhcb/LHCb/Collision24/DATA24.ROOT/00266999/0000/",
    "Bs2DsPi": "root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/anaprod/lhcb/LHCb/Collision24/DATA24.ROOT/00267010/0000/",
}

    
rule add_features_data:
    input:
        script = join(repo, 'scripts/adding_features_v2.py'),
    log: join(data, '{sample_type,(withUT_MC_2024|noUT_MC_2024)}/1_raw/{decay,(Bs2JpsiPhi|Bu2JpsiK|Bd2JpsiKst|Bd2DmPi|Bs2DsPi)}/.{id,.*}.log')
    output:
        root =join(data, '{sample_type}/1_raw/{decay}/{id}.root')
    resources:
        mem_mb = 20000, # Specify memory requirement in megabytes
        MaxRunHours = 4, # medium queue

    run:
        tree = find_tree_name(wildcards.decay)
        input_raw = join(RAW_SETTINGS[wildcards.decay], f'{wildcards.id}.root')
        cmd = [
            'python', input.script,
            '--raw', input_raw,
            '--output {output}',
            '--evtType {wildcards.decay}',
            '--treename', tree,
            '--data_calib',
            '&> {log}',
        ]
        shell(' '.join(cmd))

rule add_selection_data:
    input:
        script = join(repo, 'scripts/preSelections.py'),
        added_features = join(data, '{sample_type}/1_raw/{decay}/{id}.root'), # Raw from Jpsi are made by the rule above, with added features run already
        cut_file = join(modified_MC, 'withUT_MC_2024/DT_outputs/{cut_name}/balanced/cuts/{tagger}_preselections.txt') # Cut file is in the MC path
    output: join(data, '{sample_type,(withUT_MC_2024|noUT_MC_2024)}/3_selected/{decay,(Bs2JpsiPhi|Bu2JpsiK|Bd2JpsiKst|Bd2DmPi|Bs2DsPi)}/{tagger, (OSKaon|OSMuon|OSElectron|SSPion|SSProton|SSKaon)}/{cut_name}/{features}/{id,.*}.root'),
    log : join(data, '{sample_type,(withUT_MC_2024|noUT_MC_2024)}/3_selected/{decay,(Bs2JpsiPhi|Bu2JpsiK|Bd2JpsiKst|Bd2DmPi|Bs2DsPi)}/{tagger, (OSKaon|OSMuon|OSElectron|SSPion|SSProton|SSKaon)}/{cut_name}/{features}/.{id,.*}.log')
    run:
        cmd = [
            'python', input.script,
            '--added_features {input.added_features}',
            '--output {output}',
            '--cut_file', input.cut_file,
            '--tagger {wildcards.tagger}',
            '--features {wildcards.features}',
            '--data_calib',
            '--repo', repo,
            '&> {log}',
        ]
        shell(' '.join(cmd))

rule add_tagDec_data:
    input:
        script = join(repo, 'scripts/adding_tagDec.py'),
        selected = join(data, '{sample_type}/3_selected/{decay}/{tagger}/{cut_name}/{features}/{id}')
    output:
        root = join(data, '{sample_type,(withUT_MC_2024|noUT_MC_2024)}/4_tagged/{decay,(Bs2JpsiPhi|Bu2JpsiK|Bd2JpsiKst|Bd2DmPi|Bs2DsPi)}/{tagger,(OSKaon|OSMuon|OSElectron|SSPion|SSProton|SSKaon)}/{cut_name}/{features}/{id}'),
    log:
        join(data, '{sample_type,(withUT_MC_2024|noUT_MC_2024)}/4_tagged/{decay,(Bs2JpsiPhi|Bu2JpsiK|Bd2JpsiKst|Bd2DmPi|Bs2DsPi)}/{tagger,(OSKaon|OSMuon|OSElectron|SSPion|SSProton|SSKaon)}/{cut_name}/{features}/{id}.log'),
    params:
        #modelPrePath = lambda wildcards: join(data.replace("ntuples","Micol_trainings"), f'savedModels/{wildcards.sample_type}/{extract_decay(wildcards.tagger)}/{wildcards.tagger}/{wildcards.cut_name}/{wildcards.features}'),
        modelPrePath = lambda wildcards: join(modified_MC, f'savedModels/{wildcards.sample_type}/{extract_decay(wildcards.tagger)}/{wildcards.tagger}/{wildcards.cut_name}_balanced/{wildcards.features}'),
        taggedDataPath = join(data, '{sample_type,(withUT_MC_2024|noUT_MC_2024)}/4_tagged/{decay,(Bs2JpsiPhi|Bu2JpsiK|Bd2JpsiKst|Bd2DmPi|Bs2DsPi)}/{tagger,(OSKaon|OSMuon|OSElectron|SSPion|SSProton|SSKaon)}/{cut_name}/{features}/'),
    run:
        print(f"Processing file: {wildcards.id}")
        print(f"Selected input file: {input.selected}")

        cmd = [
            'python', input.script,
            '--selected {input.selected}',
            '--cut {wildcards.cut_name}_balanced',
            '--taggedData {output.root}',  
            '--modelPrePath {params.modelPrePath}',
            '--decayType {wildcards.decay}', # Decay used for evaluating the tagger
            '--tagger {wildcards.tagger}',
            '--features {wildcards.features}',
            '--repo', repo,
            '--data_calib',
            '&> {log}'
        ]
        shell(' '.join(cmd))