{
  "v1_set": [
    'B_OWNPV_X',
    'B_OWNPV_Y',
    'B_OWNPV_Z',
    'B_ENDV_X',
    'B_ENDV_Y',
    'B_ENDV_Z',
    'B_ENERGY',
    'B_ETA',
    'B_M',
    'B_P',
    'B_PHI',
    'B_PT',
    'B_PX',
    'B_PY',
    'B_PZ',
    'B_nPVs',
    'B_nTracks',
    'B_Tr_T_TRACKISLONG',
    'B_Tr_T_OWNPVIP',
    'B_Tr_T_OWNPVIPCHI2',
    'B_Tr_T_Charge',
    'B_Tr_T_ISMUON',
    'B_Tr_T_ENERGY',
    'B_Tr_T_Eta',
    'B_Tr_T_MINIP',
    'B_Tr_T_MINIPChi2',
    'B_Tr_T_P',
    'B_Tr_T_PT',
    'B_Tr_T_PIDK',
    'B_Tr_T_PIDe',
    'B_Tr_T_PIDmu',
    'B_Tr_T_PIDP',
    'B_Tr_T_PROBNN_GHOST',
    'B_Tr_T_PROBNN_E',
    'B_Tr_T_PROBNN_K',
    'B_Tr_T_PROBNN_P',
    'B_Tr_T_PROBNN_MU',
    'B_Tr_T_PROBNN_PI',
    'B_Tr_T_CHI2DOF',
    'B_Tr_T_GHOSTPROB',
    'B_Tr_T_PX',
    'B_Tr_T_PY',
    'B_Tr_T_PZ',
    'B_Tr_T_X',
    'B_Tr_T_Y',
    'B_Tr_T_Z',
    'B_Tr_T_IPChi2BVTX',
    'B_Tr_T_IPBVTX',


    'B_Tr_T_cos_PhiDistance',
    'B_Tr_T_PhiDistance',
    'B_Tr_T_diff_z',
    'B_Tr_T_DeltaR',
    'diff_P',
    'P_proj',
    't',
    'EVIP',
    'B_Tr_T_EtaDistance',
    'B_Tr_T_DeltaQ_Pion',
    'B_Tr_T_DeltaQ_Muon',
    'B_Tr_T_DeltaQ_Electron',
    'B_Tr_T_DeltaQ_Proton',
    'B_Tr_T_DeltaQ_Kaon',
    'B_Tr_T_Signal_TagPart_PT',
    'B_Tr_T_OWNPVIPSig',
    'logEVIP',
    'logP_proj',
    'B_Tr_T_atanPT_PZ',
  ],
  "v1_reduced_set":[
    'B_nPVs',
    'B_nTracks',
    'B_Tr_T_CHI2DOF',
    'B_Tr_T_ENERGY',
    'B_Tr_T_IPBVTX',
    'B_Tr_T_IPChi2BVTX',
    'B_Tr_T_MINIP',
    'B_Tr_T_MINIPChi2',
    'B_Tr_T_OWNPVIP',
    'B_Tr_T_OWNPVIPCHI2',
    'B_Tr_T_P',
    'B_Tr_T_PX',
    'B_Tr_T_PY',
    'B_Tr_T_PZ',
    'B_Tr_T_PT',
    'B_Tr_T_PIDK',
    'B_Tr_T_PIDe',
    'B_Tr_T_PIDmu',
    'B_Tr_T_PIDP',
    'B_Tr_T_PROBNN_GHOST',
    'B_Tr_T_PROBNN_E',
    'B_Tr_T_PROBNN_K',
    'B_Tr_T_PROBNN_P',
    'B_Tr_T_PROBNN_MU',
    'B_Tr_T_PROBNN_PI',


    'B_Tr_T_atanPT_PZ',
    'B_Tr_T_cos_PhiDistance', 
    'B_Tr_T_DeltaR', 
    'B_Tr_T_diff_z', 
    'B_Tr_T_OWNPVIPSig',
    'B_Tr_T_PhiDistance', 
    't',
  ],
  "augmented_set":
  [
    'B_nPVs',
    'B_nTracks',
    'B_Tr_T_CHI2DOF',
    'B_Tr_T_ENERGY',
    'B_Tr_T_IPBVTX',
    'B_Tr_T_IPChi2BVTX',
    'B_Tr_T_MINIP',
    'B_Tr_T_MINIPChi2',
    'B_Tr_T_OWNPVIP',
    'B_Tr_T_OWNPVIPCHI2',
    'B_Tr_T_P',
    'B_Tr_T_PX',
    'B_Tr_T_PY',
    'B_Tr_T_PZ',
    'B_Tr_T_PT',
    'B_Tr_T_PIDK',
    'B_Tr_T_PIDe',
    'B_Tr_T_PIDmu',
    'B_Tr_T_PIDP',
    'B_Tr_T_PROBNN_GHOST',
    'B_Tr_T_PROBNN_E',
    'B_Tr_T_PROBNN_K',
    'B_Tr_T_PROBNN_P',
    'B_Tr_T_PROBNN_MU',
    'B_Tr_T_PROBNN_PI',


    'B_Tr_T_cos_PhiDistance', 
    'B_Tr_T_PhiDistance', 
    'B_Tr_T_DeltaR', 
    'diff_P', 
    'P_proj', 
    't', 
    'EVIP', 
    'B_Tr_T_EtaDistance', 
    'B_Tr_T_DeltaQ_Pion', 
    'B_Tr_T_DeltaQ_Muon', 
    'B_Tr_T_DeltaQ_Electron', 
    'B_Tr_T_DeltaQ_Proton', 
    'B_Tr_T_DeltaQ_Kaon', 
    'B_Tr_T_Signal_TagPart_PT', 
    'B_Tr_T_OWNPVIPSig', 
    'logEVIP', 
    'logP_proj', 
    'B_Tr_T_atanPT_PZ',
    'B_Tr_T_endSV_Z',
    'B_Tr_T_EoverP',
    'B_Tr_T_DeltaP_X', 
    'B_Tr_T_DeltaP_Y', 
    'B_Tr_T_DeltaP_Z', 
    'B_Tr_T_DeltaP_X_abs', 
    'B_Tr_T_DeltaP_Y_abs', 
    'B_Tr_T_DeltaP_Z_abs', 
    'B_Tr_T_DeltaP', 
    'B_Tr_T_DeltaP_T', 
    'B_Tr_T_Theta', 
    'B_Theta', 
    'B_Tr_T_ThetaDistance', 
    'B_Tr_T_diff_x', 
    'B_Tr_T_diff_y', 
    'B_Tr_T_diff_z', 
    'B_Tr_T_diff_rho', 
    'B_Tr_T_diff_R', 
    'B_Tr_T_AngleSep', 
    'B_Tr_T_AngleSep_diff_z', 
    'B_Tr_T_AngleSep_diff_rho', 
    'B_Tr_T_AngleSep_diff_R', 
    'B_Tr_T_PhiDist_diff_z', 
    'B_Tr_T_PhiDist_diff_rho', 
    'B_Tr_T_PhiDist_diff_R', 
    'B_Tr_T_ThetaDist_diff_z', 
    'B_Tr_T_ThetaDist_diff_rho', 
    'B_Tr_T_ThetaDist_diff_R', 
    'B_Tr_T_ProbNN_EoverMu', 
    'B_Tr_T_ProbNN_EoverPi', 
    'B_Tr_T_ProbNN_EoverK', 
    'B_Tr_T_ProbNN_EoverP', 
    'B_Tr_T_ProbNN_MuoverE', 
    'B_Tr_T_ProbNN_MuoverPi', 
    'B_Tr_T_ProbNN_MuoverK', 
    'B_Tr_T_ProbNN_MuoverP', 
    'B_Tr_T_ProbNN_PioverE', 
    'B_Tr_T_ProbNN_PioverMu', 
    'B_Tr_T_ProbNN_PioverK', 
    'B_Tr_T_ProbNN_PioverP', 
    'B_Tr_T_ProbNN_KoverE', 
    'B_Tr_T_ProbNN_KoverMu', 
    'B_Tr_T_ProbNN_KoverPi', 
    'B_Tr_T_ProbNN_KoverP', 
    'B_Tr_T_ProbNN_PoverE', 
    'B_Tr_T_ProbNN_PoverMu', 
    'B_Tr_T_ProbNN_PoverPi', 
    'B_Tr_T_ProbNN_PoverK', 
    'B_Tr_T_ProbNN_PioverHadron', 
    'B_Tr_T_ProbNN_KoverHadron', 
    'B_Tr_T_ProbNN_PoverHadron', 
    'B_Tr_T_IPBVTX_IPChi2BVTX', 
    'B_Tr_T_MINIPChi2_IPChi2BVTX', 
    'B_Tr_T_EoverPT', 
    'B_Tr_T_ET', 
    'B_Tr_T_Rho',
    'B_Tr_T_R',
    'B_Tr_T_firstRho',
    'B_Tr_T_firstR',
    'B_Tr_T_cos_AngleSep_diff_z',
    'B_Tr_T_cos_AngleSep_diff_rho',
    'B_Tr_T_cos_AngleSep_diff_R',
    'B_Tr_T_sin_AngleSep_diff_z',
    'B_Tr_T_sin_AngleSep_diff_rho',
    'B_Tr_T_sin_AngleSep_diff_R',
    'B_Tr_T_cosPhiDist_diff_z',
    'B_Tr_T_cosPhiDist_diff_rho',
    'B_Tr_T_cosPhiDist_diff_R',
    'signal_is_Bs'
  ]
}