{
  'Bu2JpsiK': 
    [
    'B_CHI2VXNDOF',
    'B_MIN_OWNPV_IPCHI2',
    'B_ETA',
    'B_DTF_PV_Jpsi_CHI2',
    'Jpsi_OWNPV_IP',
    'muplus_OWNPV_IP',
    'muminus_OWNPV_IP',
    'hplus_ETA',
    'hplus_MINIP',
    'hplus_OWNPV_IP',
    ],
  'Bd2JpsiKst': 
    [
    'B_CHI2VXNDOF',
    'B_MIN_OWNPV_IPCHI2',
    'B_ETA',
    'B_DTF_PV_Jpsi_CHI2',
    'Jpsi_OWNPV_IP',
    'muplus_OWNPV_IP',
    'muminus_OWNPV_IP',
    'X_OWNPV_FD',
    'X_ETA',
    'X_PZ',
    'hplus_OWNPV_IP',
    'hplus_MINIP',
    'hminus_OWNPV_IP',
    'hminus_MINIP',
    ]
}