{
  'Bu2JpsiK': 
    [
      'B_CHI2VXNDOF',
      'B_MIN_OWNPV_IPCHI2',
      'B_ETA',
      'B_DTF_PV_Jpsi_CHI2',
      'Jpsi_OWNPV_IP',
      'muplus_OWNPV_IP',
      'muminus_OWNPV_IP',
      'hplus_ETA',
      'hplus_MINIP',
      'hplus_OWNPV_IP',
    ],
  'Bd2JpsiKst': 
    [
      'B_CHI2VXNDOF',
      'B_MIN_OWNPV_IPCHI2',
      'B_ETA',
      'B_DTF_PV_Jpsi_CHI2',
      'Jpsi_OWNPV_IP',
      'muplus_OWNPV_IP',
      'muminus_OWNPV_IP',
      'X_OWNPV_FD',
      'X_ETA',
      'X_PZ',
      'hplus_OWNPV_IP',
      'hplus_MINIP',
      'hminus_OWNPV_IP',
      'hminus_MINIP',
    ],
  'Bs2DsPi': 
    [
      'B_CHI2VXNDOF',
      'B_MIN_OWNPV_IPCHI2',
      'B_ETA',
      'B_DTF_PV_Ds_CHI2',
      'Ds_OWNPV_IP',
      'Ds_OWNPV_FD',
      'Ds_ETA',
      'Ds_PZ',
      'hplus_OWNPV_IP',
      'hminus_OWNPV_IP',
      'piminus_OWNPV_IP',
      'piplus_OWNPV_IP',
      'hplus_MINIP',
      'hminus_MINIP',
      'piminus_MINIP',
      'piplus_MINIP',
    ]
}