# Snakefile
taggers = ["SSPion", "SSProton", "SSKaon", "OSKaon", "OSMuon", "OSElectron"]

# Snakefile

# Define a function to read the list of taggers from the file
def read_args():
    with open("taggers.txt", "r") as file:
        return [line.strip() for line in file]
# Define the target rule to generate a list of taggers
rule all:
    input:
        expand("/ceph/users/molocco/classical-taggers/scripts/outputSnake/{arg}.out", arg=taggers)

